### ISSUE TITLE
Unable to frame images if custom font not given

### ISSUE THREAD

**Issue by ayushgoel** [fastlane/frameit#51]
In case I do not specify a custom font in `Framefile.json` i.e. comment out any of the `font` keys in the following snippet, `frameit` fails. This happens when in backtrace, it says `using the default one`.
```
  "default": {
    "keyword": {
      "font": "SassyMolassy.ttf"
    },
    "title": {
      "fonts": [
        {
          "font": "SassyMolassy.ttf",
          "supported": ["en-US"]
        }
      ]
    },
```

Here is the backtrace:

```
[37mINFO [2015-09-20 01:23:03.53]: [0m[33mParsing config file 'screenshots/Framefile.json'[0m
[35mDEBUG [2015-09-20 01:23:05.70]: [0mNo custom font specified for ./screenshots/en-US/en-US-iPhone5-0-LandingScreen-portrait.png, using the default one
[35mDEBUG [2015-09-20 01:23:05.71]: [0mAdding text 'Landing Keyword'
[31mERROR [2015-09-20 01:23:05.75]: [0m`mogrify -gravity Center -pointsize 49 -draw text 0,0 'Landing Keyword' -fill #d21559 /var/folders/s8/g0nkp8b577v5whf_wk_lzms40000gp/T/mini_magick20150920-12010-8yxi9x.png` failed with error:
mogrify: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1153.
mogrify: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1153.
mogrify: non-conforming drawing primitive definition `text' @ error/draw.c/DrawImage/3173.

[31mERROR [2015-09-20 01:23:05.75]: [0mBacktrace:
	/gems/mini_magick-4.0.4/lib/mini_magick/shell.rb:22:in `run'
	/gems/mini_magick-4.0.4/lib/mini_magick/tool.rb:92:in `call'
	/gems/mini_magick-4.0.4/lib/mini_magick/tool.rb:53:in `new'
	/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:492:in `mogrify'
	/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:367:in `combine_options'
	/gems/frameit-2.2.1/lib/frameit/editor.rb:229:in `block in build_title_images'
	/gems/frameit-2.2.1/lib/frameit/editor.rb:213:in `each'
	/gems/frameit-2.2.1/lib/frameit/editor.rb:213:in `build_title_images'
	/gems/frameit-2.2.1/lib/frameit/editor.rb:156:in `add_title'
	/gems/frameit-2.2.1/lib/frameit/editor.rb:102:in `complex_framing'
	/gems/frameit-2.2.1/lib/frameit/editor.rb:17:in `frame!'
	/gems/frameit-2.2.1/lib/frameit/screenshot.rb:72:in `frame!'
	/gems/frameit-2.2.1/lib/frameit/runner.rb:29:in `block in run'
	/gems/frameit-2.2.1/lib/frameit/runner.rb:21:in `each'
	/gems/frameit-2.2.1/lib/frameit/runner.rb:21:in `run'
	/gems/frameit-2.2.1/bin/frameit:31:in `block (2 levels) in run'
	/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	/gems/commander-4.3.5/lib/commander/runner.rb:71:in `run!'
	/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	/gems/frameit-2.2.1/bin/frameit:55:in `run'
	/gems/frameit-2.2.1/bin/frameit:63:in `<top (required)>'
	/bin/frameit:23:in `load'
	/bin/frameit:23:in `<main>'
	/bin/ruby_executable_hooks:15:in `eval'
	/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jaylyerly** [comment]
I had the same problem.  Seems like there's something wrong with ImageMagick (mogrify) being able to find fonts.  

As per this SO: http://stackoverflow.com/questions/28043993/rmagick-unable-to-read-font, you can fix it with 

brew install gs

Not sure why, but I suspect the ghostscript installation causes a system level font cache to be (re)built.

**Comment by KrauseFx** [comment]
Yeah, you'll have to install the fonts manually
